// CRITERIUM COMPÁS: escala de acento esmeralda (sustituye el índigo de Twenty).
const EMERALD_LIGHT = {
  emerald1: '#f8fdfb',
  emerald2: '#f0faf5',
  emerald3: '#e2f7ec',
  emerald4: '#d0f2e1',
  emerald5: '#bdebd4',
  emerald6: '#a3e1c4',
  emerald7: '#7ed3ae',
  emerald8: '#48bf91',
  emerald9: '#10b981',
  emerald10: '#0ea372',
  emerald11: '#047857',
  emerald12: '#0b3b2d',
};

export const ACCENT_LIGHT = {
  primary: EMERALD_LIGHT.emerald5,
  secondary: EMERALD_LIGHT.emerald5,
  tertiary: EMERALD_LIGHT.emerald3,
  quaternary: EMERALD_LIGHT.emerald2,
  accent3570: EMERALD_LIGHT.emerald8,
  accent4060: EMERALD_LIGHT.emerald8,
  accent1: EMERALD_LIGHT.emerald1,
  accent2: EMERALD_LIGHT.emerald2,
  accent3: EMERALD_LIGHT.emerald3,
  accent4: EMERALD_LIGHT.emerald4,
  accent5: EMERALD_LIGHT.emerald5,
  accent6: EMERALD_LIGHT.emerald6,
  accent7: EMERALD_LIGHT.emerald7,
  accent8: EMERALD_LIGHT.emerald8,
  accent9: EMERALD_LIGHT.emerald9,
  accent10: EMERALD_LIGHT.emerald10,
  accent11: EMERALD_LIGHT.emerald11,
  accent12: EMERALD_LIGHT.emerald12,
};
